### ISSUE TITLE
Add Debug bound?

### ISSUE THREAD

**Issue by Manishearth** [rust-fuzz/rust_arbitrary#7]
Would be useful for https://github.com/rust-fuzz/libfuzzer-sys/pull/48 . We can also solve it there with some tricks, though.

**Comment by fitzgen** [comment]
Thinking about this some more, I don't think we should require a `Debug` super trait, since this would mostly be useful for consumers of `Arbitrary` instances, not implementers.

And consumers always have a working solution to this problem: explicitly add `Debug` as an additional trait bound.

(For libfuzzer-sys it is a little weird, since its usage is inside a macro, but the point still stands in general)

Unless you disagree, @Manishearth, I'll close this issue.
